### ISSUE TITLE
Change for BNB

### ISSUE THREAD

**Issue by MauMorhy** [sorenrood/eth-transfer#1]
Is it possible to put this code to work with BNB? I have a hacked MetaMask account that the hack transfers all Bcoins (BombCypto) and BNBs to his target, would it be possible to adapt this code to do the same and I compete with his BOT?

**Comment by sorenrood** [comment]
Possibly @MauMorhy -- you might find [this](https://paohuee.medium.com/interact-binance-smart-chain-using-python-4f8d745fe7b7) useful.

**Comment by MauMorhy** [comment]
> Possibly @MauMorhy -- you might find [this](https://paohuee.medium.com/interact-binance-smart-chain-using-python-4f8d745fe7b7) useful.

By your code and by the information on the site, I can send BNB but not another Token like Bcoin, could you guide me please, it's really important.
